# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Hands-On Astrodynamics tutrial
author: Sho Nishimura
logo: media/logo.png
exclude_patterns: [.DS_Store, "**.ipynb_checkpoints", "**.pytest_cache", "tools"]

# Launch on Google Colab button
launch_buttons:
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"

# only build files that appear in toc
only_build_toc_files: true

# # Parse and render settings
parse:
   myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
       - html_image
       - colon_fence
       - amsmath
       - dollarmath

sphinx:
  extra_extensions:
    - sphinx_proof

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: MO-book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Sho1930/Astro-book  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "rocket.ico"
  use_raw_html: true
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: true   # Continuous numbering across parts/chapters
  google_analytics_id: G-DVQ7NZ8CYZ
  
